---
- hosts: localhost
  gather_facts: no
  roles:
    - hoplacloud.windows_get_password

- hosts: "{{ instance_name }}"
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_host: "{{openstack.metadata.ssh_pub_ip}}"
    ansible_port: "{{openstack.metadata.ssh_pub_port}}"
    ansible_user: Admin
    ansible_password: "{{hostvars['localhost']['windows_passwords'][inventory_hostname]}}"
  roles:
    - hoplacloud.windows_base

- hosts: meta-is_ad_true
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_host: "{{openstack.metadata.ssh_pub_ip}}"
    ansible_port: "{{openstack.metadata.ssh_pub_port}}"
    ansible_user: Admin
    ansible_password: "{{hostvars['localhost']['windows_passwords'][inventory_hostname]}}"
  roles:
    - hoplacloud.windows_ad

- hosts: "{{ instance_name }}"
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_host: "{{openstack.metadata.ssh_pub_ip}}"
    ansible_port: "{{openstack.metadata.ssh_pub_port}}"
    ansible_user: Admin
    ansible_password: "{{hostvars['localhost']['windows_passwords'][inventory_hostname]}}"
  roles:
    - hoplacloud.windows_ad
