---
- hosts: localhost
  gather_facts: no
  roles:
    - hoplacloud.windows_get_password

- hosts: "{{ instance_name }}"
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_host: "{{hostvars[instance_name]['openstack'].ssh_pub_ip}}"
    ansible_port: "{{hostvars[instance_name]['openstack'].ssh_pub_port|int}}"
    ansible_user: Admin
    ansible_password: "{{hostvars['localhost']['windows_passwords']}}.{{instance_name}}"
  roles:
    - hoplacloud.windows_base
