---
- hosts: localhost
  gather_facts: no
  roles:
    - hoplacloud.windows_get_disk

- hosts: "{{ instance_name }}"
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_host: "{{openstack.metadata.ssh_pub_ip}}"
    ansible_port: "{{openstack.metadata.ssh_pub_port}}"
  roles:
    - hoplacloud.windows_base
    - hoplacloud.windows_init_disk

- hosts: "*chr1"
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_network_os: routeros
    ansible_user: admin
    ansible_password: "{{mikrotik_admin_password}}"
  roles:
    - hoplacloud.windows_ad_mikrotik_dns

- hosts: "{{ instance_name }}"
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_host: "{{openstack.metadata.ssh_pub_ip}}"
    ansible_port: "{{openstack.metadata.ssh_pub_port}}"
  roles:
    - hoplacloud.windows_ad_join

- hosts: "{{ instance_name }}"
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_host: "{{openstack.metadata.ssh_pub_ip}}"
    ansible_port: "{{openstack.metadata.ssh_pub_port}}"
  roles:
    - hoplacloud.windows_rds_std
