---
# tasks file for hoplacloud.windows_ad_join
- name: Set fact ad_domain
  set_fact:
    ad_domain: "{{ ad_domain_name | regex_replace('\\.', ',DC=') | regex_replace('^(.*)$', 'DC=\\1') }}"
#    domain_state1.reboot_required: false
#    domain_state2.reboot_required: false

- name: Ensure the server is present in the active directory
  win_domain_membership:
      dns_domain_name: "{{ ad_domain_name }}"
      domain_admin_user: administrator
      domain_admin_password: "{{ administrator_password }}"
      domain_ou_path: "OU=Servers,OU=ORGANIZATION,{{ ad_domain }}"
      state: domain
  register: domain_state1
  when: "'meta-is_rds_std_true' not in group_names and 'meta-is_ad_true' not in group_names"

- name: Reboot if required
  win_reboot:
  when: "domain_state1.reboot_required and 'meta-is_rds_std_true' not in group_names and 'meta-is_ad_true' not in group_names"

- name: Ensure the server is present in the active directory
  win_domain_membership:
      dns_domain_name: "{{ ad_domain_name }}"
      domain_admin_user: administrator
      domain_admin_password: "{{ administrator_password }}"
      domain_ou_path: "OU=RDS,OU=Servers,OU=ORGANIZATION,{{ ad_domain }}"
      state: domain
  register: domain_state2
  when: "'meta-is_rds_std_true' in group_names"

- name: Reboot if required
  win_reboot:
  when: "domain_state2.reboot_required and 'meta-is_rds_std_true' in group_names"
