---
# tasks file for hoplacloud.windows_ad_join
- name: Set fact ad_domain
  set_fact:
    ad_domain: "{{ ad_domain_name | regex_replace('\\.', ',DC=') | regex_replace('^(.*)$', 'DC=\\1') }}"

- name: Ensure the server is present in the active directory (Other RDS servers)
  block:
    - name: Join domain
      win_domain_membership:
        dns_domain_name: "{{ ad_domain_name }}"
        domain_admin_user: "{{ad_netbios_name}}\\administrator"
        domain_admin_password: "{{ administrator_password }}"
        domain_ou_path: "OU=Servers,OU=ORGANIZATION,{{ ad_domain }}"
        state: domain
      register: domain_state1
    - name: Reboot if required
      win_reboot:
      when: domain_state1.reboot_required
    - name: Ensure DNS register
      win_shell: ipconfig /registerdns
  when: "'meta-is_rds_std_true' not in group_names and 'meta-is_ad_true' not in group_names"

- name: Ensure the server is present in the active directory (Other RDS servers)
  block:
    - name: Join domain
      win_domain_membership:
        dns_domain_name: "{{ ad_domain_name }}"
        domain_admin_user: "{{ad_netbios_name}}\\administrator"
        domain_admin_password: "{{ administrator_password }}"
        domain_ou_path: "OU=RDS,OU=Servers,OU=ORGANIZATION,{{ ad_domain }}"
        state: domain
      register: domain_state2
    - name: Reboot if required
      win_reboot:
      when: domain_state2.reboot_required
    - name: Ensure DNS register
      win_shell: ipconfig /registerdns
  when: "'meta-is_rds_std_true' in group_names"
