---
# tasks file for hoplacloud.windows_ad_join
- name: Set fact ad_domain
  set_fact:
    ad_domain: "{{ ad_domain_name | regex_replace('\\.', ',DC=') | regex_replace('^(.*)$', 'DC=\\1') }}"

- name: Ensure the server is present in the active directory
  win_domain_membership:
      dns_domain_name: "{{ ad_domain_name }}"
      domain_admin_user: administrator
      domain_admin_password: "{{ administrator_password }}"
      domain_ou_path: "OU=Servers,OU=ORGANIZATION,{{ ad_domain }}"
      state: domain
  register: domain_state

- name: Reboot if required
  win_reboot:
  when: domain_state.reboot_required
