---
# tasks file for hoplacloud.windows_ad_join
- name: Set fact ad_domain
  set_fact:
    ad_domain: "{{ ad_domain_name | regex_replace('\\.', ',DC=') | regex_replace('^(.*)$', 'DC=\\1') }}"
  when: ('meta-is_ad_true' in groups)

- name: Ensure the server is present in the active directory (Other RDS servers)
  block:
    - name: Wait DNS resolution
      win_shell: |
        $count = 0
          do{
            try{
                ipconfig /flushdns
                Resolve-DnsName "{{ad_domain_name}}" -ErrorAction Stop
                $success = $true
            }catch{
              Write-Output "Next attempt in 15 seconds"
              Start-sleep -Seconds 15
            }
            $count++
          }until($count -eq 15 -or $success)
        if(-not($success)){exit}
      changed_when: false

    - name: Join domain EN
      win_domain_membership:
        dns_domain_name: "{{ ad_domain_name }}"
        domain_admin_user: "{{ad_netbios_name}}\\administrator"
        domain_admin_password: "{{ administrator_password }}"
        domain_ou_path: "OU=Servers,OU=ORGANIZATION,{{ ad_domain }}"
        state: domain
      register: domain_state_EN
      when: "'EN' in ad_language"

    - name: Join domain FR
      win_domain_membership:
        dns_domain_name: "{{ ad_domain_name }}"
        domain_admin_user: "{{ad_netbios_name}}\\administrateur"
        domain_admin_password: "{{ administrator_password }}"
        domain_ou_path: "OU=Servers,OU=ORGANIZATION,{{ ad_domain }}"
        state: domain
      register: domain_state_FR
      when: "'FR' in ad_language"

    - name: Reboot if required
      win_reboot:
      when: "'EN' in ad_language and domain_state_EN.reboot_required"

    - name: Reboot if required
      win_reboot:
      when: "'FR' in ad_language and domain_state_FR.reboot_required"

    - name: Ensure DNS register
      win_shell: ipconfig /registerdns
  when: "'meta-is_ad_true' not in group_names and 'meta-is_rds_host_true' not in group_names and 'meta-is_ad_true' in groups"

- name: Move computer OU
  win_domain_computer:
    name: "{{item}}"
    dns_hostname: "{{item}}.{{ad_domain_name}}"
    ou: "OU=Servers,OU=ORGANIZATION,{{ ad_domain }}"
  loop: "{{ query('inventory_hostnames', 'meta-is_windows_true:!meta-is_rds_host_true:!meta-is_ad_true:!meta-is_ad_sec_true') }}"
  when: "'meta-is_ad_true' in group_names"

- name: Ensure the server is present in the active directory (RDS servers)
  block:
    - name: Wait DNS resolution
      win_shell: |
        $count = 0
          do{
            try{
                ipconfig /flushdns
                Resolve-DnsName "{{ad_domain_name}}" -ErrorAction Stop
                $success = $true
            }catch{
              Write-Output "Next attempt in 15 seconds"
              Start-sleep -Seconds 15
            }
            $count++
          }until($count -eq 15 -or $success)
        if(-not($success)){exit}
      changed_when: false

    - name: Join domain RDS EN
      win_domain_membership:
        dns_domain_name: "{{ ad_domain_name }}"
        domain_admin_user: "{{ad_netbios_name}}\\administrator"
        domain_admin_password: "{{ administrator_password }}"
        state: domain
      register: domain_state_rds_EN
      when: "'EN' in ad_language"

    - name: Join domain RDS FR
      win_domain_membership:
        dns_domain_name: "{{ ad_domain_name }}"
        domain_admin_user: "{{ad_netbios_name}}\\administrateur"
        domain_admin_password: "{{ administrator_password }}"
        state: domain
      register: domain_state_rds_FR
      when: "'FR' in ad_language"

    - name: Reboot if required (RDS EN)
      win_reboot:
      when: "'EN' in ad_language and domain_state_rds_EN.reboot_required"

    - name: Reboot if required (RDS FR)
      win_reboot:
      when: "'FR' in ad_language and domain_state_rds_FR.reboot_required"

    - name: Ensure DNS register
      win_shell: ipconfig /registerdns
  when: "'meta-is_rds_host_true' in group_names and 'meta-is_ad_true' not in group_names and 'meta-is_ad_true' in groups"
