---
# tasks file for hoplacloud.windows_ad_mikrotik_dns
- name: Récupération du serveur Windows Active Directory
  set_fact:
    windows_instances_ad_name: "{{item}}"
  with_items: "{{ groups['meta-is_windows_true'] }}"

- name: Récupération de l'adresse ip du serveur Windows Active Directory
  set_fact:
    windows_instances_ad_ip: "{{hostvars[windows_instances_ad_name]['ansible_ip_addresses'][0]}}"

- name: Configuration du server DNS
  routeros_command:
    commands: /ip dns set allow-remote-requests=yes server="{{windows_instances_ad_ip}}"
