---
# tasks file for hoplacloud.windows_rds_ad

- name: Get DistinguishedName
  win_shell: (Get-ADDomain).DistinguishedName
  register: ad_domain
  changed_when: ad_domain.rc == 1

- name: Set fact ad_domain
  set_fact:
    ad_domain: "{{ ad_domain.stdout_lines[0] }}"

- name: Ensure GG_USR_RDS is present
  win_domain_group:
    name: GG_USR_RDS
    scope: global
    path: "OU=Security groups,OU=ORGANIZATION,{{ ad_domain }}"

- name: Ensure GG_USR_EN is present
  win_domain_group:
    name: GG_USR_EN
    scope: global
    path: "OU=Security groups,OU=ORGANIZATION,{{ ad_domain }}"

- name: Ensure GG_USR_FR is present
  win_domain_group:
    name: GG_USR_FR
    scope: global
    path: "OU=Security groups,OU=ORGANIZATION,{{ ad_domain }}"

- name: Create directory scripts
  win_file:
    path: C:\scripts
    state: directory

- name: Ensure GPO RDS_SERVERS is present
  win_shell: |
    $gpo_check = (Get-GPO -all ).DisplayName
    if ($gpo_check -notcontains "_RDS_SERVERS"){
    New-GPO -Name "_RDS_SERVERS"
    Write-Host Change
    }
  register: ad_gpo_rds_servers_create
  changed_when: ("Change" in ad_gpo_rds_servers_create.stdout)

- name: Ensure GPO RDS_USERS is present
  win_shell: |
    $gpo_check = (Get-GPO -all ).DisplayName
    if ($gpo_check -notcontains "_RDS_USERS"){
    New-GPO -Name "_RDS_USERS"
    Write-Host Change
    }
  register: ad_gpo_rds_users_create
  changed_when: ("Change" in ad_gpo_rds_users_create.stdout)

- name: Ensure GPO RDS_USERS_EN is present
  win_shell: |
    $gpo_check = (Get-GPO -all ).DisplayName
    if ($gpo_check -notcontains "_RDS_USERS_EN"){
    New-GPO -Name "_RDS_USERS_EN"
    Write-Host Change
    }
  register: ad_gpo_rds_users_en_create
  changed_when: ("Change" in ad_gpo_rds_users_en_create.stdout)

- name: Ensure GPO RDS_USERS_FR is present
  win_shell: |
    $gpo_check = (Get-GPO -all ).DisplayName
    if ($gpo_check -notcontains "_RDS_USERS_FR"){
    New-GPO -Name "_RDS_USERS_FR"
    Write-Host Change
    }
  register: ad_gpo_rds_users_fr_create
  changed_when: ("Change" in ad_gpo_rds_users_fr_create.stdout)

- name: Ensure GPO RDS_SERVERS is linked
  win_shell: |
    [xml]$gpoReport = Get-GPOReport -Name _RDS_SERVERS -ReportType xml
    if ($gpoReport.GPO.LinksTo.Enabled -notlike "true"){
    new-GPLink -Name "_RDS_SERVERS" -Target "OU=RDS,OU=Servers,OU=ORGANIZATION,{{ ad_domain }}" -LinkEnabled Yes
    Write-Host Change
    }
  register: ad_gpo_rds_servers_link_create
  changed_when: ("Change" in ad_gpo_rds_servers_link_create.stdout)

- name: Ensure GPO RDS_USERS is linked
  win_shell: |
    [xml]$gpoReport = Get-GPOReport -Name _RDS_USERS -ReportType xml
    if ($gpoReport.GPO.LinksTo.Enabled -notlike "true"){
    new-GPLink -Name "_RDS_USERS" -Target "OU=Users,OU=ORGANIZATION,{{ ad_domain }}" -LinkEnabled Yes
    Write-Host Change
    }
  register: ad_gpo_rds_users_link_create
  changed_when: ("Change" in ad_gpo_rds_users_link_create.stdout)

- name: Ensure GPO RDS_USERS_EN is linked
  win_shell: |
    [xml]$gpoReport = Get-GPOReport -Name _RDS_USERS_EN -ReportType xml
    if ($gpoReport.GPO.LinksTo.Enabled -notlike "true"){
    new-GPLink -Name "_RDS_USERS_EN" -Target "OU=Users,OU=ORGANIZATION,{{ ad_domain }}" -LinkEnabled Yes
    Write-Host Change
    }
  register: ad_gpo_rds_users_en_link_create
  changed_when: ("Change" in ad_gpo_rds_users_en_link_create.stdout)

- name: Ensure GPO RDS_USERS_FR is linked
  win_shell: |
    [xml]$gpoReport = Get-GPOReport -Name _RDS_USERS_FR -ReportType xml
    if ($gpoReport.GPO.LinksTo.Enabled -notlike "true"){
    new-GPLink -Name "_RDS_USERS_FR" -Target "OU=Users,OU=ORGANIZATION,{{ ad_domain }}" -LinkEnabled Yes
    Write-Host Change
    }
  register: ad_gpo_rds_users_fr_link_create
  changed_when: ("Change" in ad_gpo_rds_users_fr_link_create.stdout)

- name: Copy ADMX FSlogix Files [1/2]
  win_copy:
    src: fslogix.admx
    dest: C:\Windows\PolicyDefinitions\fslogix.admx

- name: Copy ADMX FSlogix Files [2/2]
  win_copy:
    src: fslogix.adml
    dest: C:\Windows\PolicyDefinitions\en-US\fslogix.adml

- name: Copy Associations Files [2/2]
  win_copy:
    src: FilesAssociations.xml
    dest: C:\Windows\SYSVOL\domain\scripts\FilesAssociations.xml

- name: Set GPO options "_RDS_SERVERS"
  win_shell: |
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\Software\Policies\Google\Chrome\ExtensionInstallForcelist" -ValueName "1" -Type string  -Value "klbibkeccnjlkjkiokjodocebajanakg;https://clients2.google.com/service/update2/crx"
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\Software\Policies\Microsoft\Windows\Server\ServerManager" -ValueName "DoNotOpenAtLogon" -Type DWORD  -Value 1
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\Software\Policies\Microsoft\Windows\System" -ValueName "DefaultAssociationsConfiguration" -Type string  -Value "\\{{ ansible_windows_domain }}\NETLOGON\FilesAssociations.xml"
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SYSTEM\ControlSet001\Services\AdobeARMservice" -ValueName "Start" -Type DWORD  -Value 4
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SYSTEM\ControlSet001\Services\WSearch" -ValueName "Start" -Type DWORD  -Value 2
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" -ValueName "AdobeAAMUpdater-1.0" -Disable
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" -ValueName "AdobeGCInvoker-1.0" -Disable
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" -ValueName "MmsMonitor.exe" -Disable
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run" -ValueName "SunJavaUpdateSched" -Disable
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run" -ValueName "Acrobat Assistant 8.0" -Disable
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run" -ValueName "AcronisTibMounterMonitor" -Disable
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run" -ValueName "Acronis Scheduler2 Service" -Disable
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\Policies\Google\Chrome" -ValueName "ChromeCleanupEnabled" -Type DWORD  -Value 0
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\Policies\Google\Chrome" -ValueName "ChromeCleanupReportingEnabled" -Type DWORD  -Value 0
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\FSLogix\Profiles" -ValueName "Enabled" -Type DWORD  -Value 1
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\FSLogix\Profiles" -ValueName "IsDynamic" -Type DWORD  -Value 1
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\FSLogix\Profiles" -ValueName "RoamSearch" -Type DWORD  -Value 2
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\FSLogix\Profiles" -ValueName "SizeInMBs" -Type DWORD  -Value 10240

- name: Set profiles server list
  set_fact:
    prf_share: "type=smb,connectionString=\\\\{{item}}\\profiles$"
  with_items: "{{ groups['meta-is_rds_prf_true'] }}"
  when: "groups['meta-is_rds_prf_true'] | length < 2"

- name: Set profiles servers list HA [1/3]
  set_fact:
    prf_share: ""
    prf_pre: "type=smb,connectionString=\\\\"
    prf_post: "\\profiles$"
  with_items: "{{ groups['meta-is_rds_prf_true'] }}"
  when: "groups['meta-is_rds_prf_true'] | length >= 2"

- name: Set profiles servers list HA [2/3]
  set_fact:
    prf_share: "{{prf_share + prf_pre item prf_post}}"
  with_items: "{{ groups['meta-is_rds_prf_true'] }}"
  when: "groups['meta-is_rds_prf_true'] | length >= 2"

- name: Set profiles servers list HA [3/3]
  set_fact:
    prf_share: "{{prf_share | replace('profiles$type','profiles$;type') }}"
  when: "groups['meta-is_rds_prf_true'] | length >= 2"

- name: Set GPO options fslogix "_RDS_SERVERS"
  win_shell: |
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\FSLogix\Profiles" -ValueName "CCDLocations" -Type String  -Value "{{prf_share}}"
  with_items: "{{ groups['meta-is_rds_prf_true'] }}"
  when: "'meta-is_rds_gw_true' in groups"

- name: Set GPO options fslogix "_RDS_SERVERS" RDS STD
  win_shell: |
    Set-GPRegistryValue -Name "_RDS_SERVERS" -Key "HKLM\SOFTWARE\FSLogix\Profiles" -ValueName "CCDLocations" -Type String  -Value "type=smb,connectionString=\\{{ansible_hostname }}\profiles$"
  with_items: "{{ groups['meta-is_rds_std_true'] }}"
  when: "'meta-is_rds_std_true' in groups"

- name: Set GPO options "_RDS_USERS"
  win_shell: |
    Set-GPRegistryValue -Name "_RDS_USERS" -Key "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" -ValueName "Adobe Acrobat Synchronizer" -Disable
    Set-GPRegistryValue -Name "_RDS_USERS" -Key "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" -ValueName "Adobe Reader Synchronizer" -Disable
    Set-GPRegistryValue -Name "_RDS_USERS" -Key "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" -ValueName "CCXProcess" -Disable
    Set-GPRegistryValue -Name "_RDS_USERS" -Key "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" -ValueName "com.squirrel.Teams.Teams" -Disable
    Set-GPRegistryValue -Name "_RDS_USERS" -Key "HKCU\Software\Microsoft\Office\16.0\Common\Identity" -ValueName "DisableADALatopWAMOverride" -Type DWORD  -Value 1

- name: Set GPO options "_RDS_USERS_EN"
  win_shell: |
    Set-GPRegistryValue -Name "_RDS_USERS_EN" -Key "HKCU\Keyboard Layout\Preload" -ValueName "1" -Type String  -Value "0x0409"
    Set-GPRegistryValue -Name "_RDS_USERS_EN" -Key "HKCU\Software\Policies\Microsoft\Control Panel\Desktop" -ValueName "PreferredUILanguages" -Type String  -Value "en-US"
    set-GPPermission -Name _RDS_USERS_EN -PermissionLevel GpoApply -TargetName GG_USR_EN -TargetType Group -Replace
    set-GPPermission -Name _RDS_USERS_EN -PermissionLevel GpoRead -TargetName "Authenticated Users" -TargetType Group -Replace -Confirm:$false

- name: Set GPO options "_RDS_USERS_FR"
  win_shell: |
    Set-GPRegistryValue -Name "_RDS_USERS_FR" -Key "HKCU\Keyboard Layout\Preload" -ValueName "1" -Type String  -Value "0x040c"
    Set-GPRegistryValue -Name "_RDS_USERS_FR" -Key "HKCU\Software\Policies\Microsoft\Control Panel\Desktop" -ValueName "PreferredUILanguages" -Type String  -Value "fr-FR"
    set-GPPermission -Name _RDS_USERS_FR -PermissionLevel GpoApply -TargetName GG_USR_FR -TargetType Group -Replace
    set-GPPermission -Name _RDS_USERS_FR -PermissionLevel GpoRead -TargetName "Authenticated Users" -TargetType Group -Replace -Confirm:$false
