---
# tasks file for hoplacloud.windows_ad

- name: Ensure user Administrator account password never expire
  win_user:
    name: administrator
    password: "{{ administrator_password }}"
    password_never_expires: yes
    account_disabled: no

- name: Install Active Directory with sub features and management tools
  win_feature:
    name: AD-Domain-Services
    state: present
    include_sub_features: yes
    include_management_tools: yes

- name: Create new domain in a new forest on the target host
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_password }}"
    domain_netbios_name: "{{ ad_netbios_name }}"
  register: domain_install

- name: Reboot server
  win_reboot:
    reboot_timeout: 3600
  when: domain_install.changed

- name: Get DistinguishedName
  win_shell: (Get-ADDomain).DistinguishedName
  register: ad_domain
  changed_when: ad_domain.rc == 1

- name: Set fact ad_domain
  set_fact:
    ad_domain: "{{ ad_domain.stdout_lines[0] }}"

- name: Ensure all Organizational Unit is present [1/x]
  win_shell:  New-ADOrganizationalUnit -Name "ORGANIZATION" -Path "{{ ad_domain }}"

- name: Ensure all Organizational Unit is present [1/x]
  win_shell:  New-ADOrganizationalUnit -Name "Admins" -Path "OU=ORGANIZATION,{{ ad_domain }}"

- name: Ensure all Organizational Unit is present [1/x]
  win_shell:  New-ADOrganizationalUnit -Name "Users" -Path "OU=ORGANIZATION,{{ ad_domain }}"

- name: Ensure all Organizational Unit is present [1/x]
  win_shell:  New-ADOrganizationalUnit -Name "Security groups" -Path "OU=ORGANIZATION,{{ ad_domain }}"

- name: Ensure all Organizational Unit is present [1/x]
  win_shell:  New-ADOrganizationalUnit -Name "Servers" -Path "OU=ORGANIZATION,{{ ad_domain }}"
