---
# tasks file for hoplacloud.windows_base

- name: Disable firewall
  win_firewall:
    state: disabled

- name: Ensure user Admin account password never expire
  win_user:
    name: admin
    password_never_expires: yes
    update_password: on_create

- name: Ensure user Administrator is disabled
  win_user:
    name: administrator
    account_disabled: yes

- name: Set windows edition to datacenter
  win_shell: dism /online /set-edition:ServerDatacenter /ProductKey:WMDGN-G9PQG-XVVXX-R3X43-63DFG /AcceptEula /NoRestart
  when: ansible_os_name == "Microsoft Windows Server 2019 Datacenter Evaluation"
  register: win_edition
  changed_when: win_edition.rc == 1
  ignore_errors: True

- name: Reboot server
  win_reboot:
    reboot_timeout: 3600
  when: win_edition.changed

- name: Enable Windows Update Active Hours
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: SetActiveHours
    data: 1
    type: dword

- name: Set Windows Update Active Hours Start
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: ActiveHoursStart
    data: 6
    type: dword

- name: Set Windows Update Active Hours End
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: ActiveHoursEnd
    data: 15
    type: dword

- name: Copy Background Desktop PNG
  win_copy:
    src: Desktop-hopla.cloud.png
    dest: C:\Program Files\hopla.cloud\Desktop-hopla.cloud.png

- name: Set Background Desktop for current user
  win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System
    name: Wallpaper
    data: C:\Program Files\hopla.cloud\Desktop-hopla.cloud.png
    type: string

- name: Set Background Desktop for current user
  win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System
    name: WallpaperStyle
    data: 4
    type: string

#- name: Install all security, critical, and rollup updates without a scheduled task and reboot if needed.
#  win_updates:
#    reboot: yes
