---
- name: Init list
  set_fact:
    windows_instances_list_name: []

#- debug:
#    msg: "{{ item }}"
#  loop: "{{ query('inventory_hostnames', 'all:!meta-is_windows_true') }}"

- name: Creation de la list des serveurs windows
  set_fact:
    windows_instances_list_name: "{{ windows_instances_list_name }} + ['{{item}}']"
  with_items: "{{ groups['meta-is_windows_true'] }}"

- os_auth:
- os_client_config:
  register: client_conf

- name: Get openstack projects list
  uri:
    url: "https://fr-east-1.pub.hopla.cloud:13000/v3/auth/projects"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ auth_token }}"
  register: projects_list_os

- name: Set project id
  set_fact:
    project_id: "{{projects_list_os.json.projects[0].id}}"

- name: Get openstack volumes list
  uri:
    url: "https://fr-east-1.pub.hopla.cloud:13776/v3/{{project_id}}/volumes"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ auth_token }}"
  register: volumes_list_os

- name: Creation des list name et id
  set_fact:
    volumes_name: "{{ volumes_list_os.json.volumes | json_query('[].name') }}"
    volumes_id: "{{ volumes_list_os.json.volumes | json_query('[].id') }}"

- name: Create list volumes_id and volumes_name
  set_fact:
    volumes_list1: "{{ dict(volumes_id | zip(volumes_name)) }}"
    volumes_list2: "{{ dict(volumes_name | zip(volumes_id)) }}"



#- name: Create list volumes_id volumes_name
#  set_fact:
#    volumes_list1: "{{ volumes_list1 | combine({item.0: item.1}) }}"
#  with_together:
#    - "{{ volumes_id }}"
#    - "{{ volumes_name }}"

#- name: Create list volumes_name volumes_id
#  set_fact:
#    volumes_list2: "{{ volumes_list2 | combine({item.1: item.0}) }}"
#  with_together:
#    - "{{ volumes_id }}"
#    - "{{ volumes_name }}"

#- name: populate volumes list
#  set_fact:
#    volumes_list: "{{volumes_list + ['{ combined_var|default({})|combine({item.0: item.1}) }'] }}"
#  loop: "{{ query('together', volumes_id, volumes_name) }}"

- name: Creation de la list des volumes attachés aux instances
  set_fact:
    "windows_disk_{{item}}": "{{hostvars[item]['openstack'].volumes}}"
  with_items: "{{ windows_instances_list_name }}"


- name: Test
  set_fact:
    test_id: "6f42c5a7-1607-4287-ad28-ff655e356f17"

- name: Test
  set_fact:
    test: "{{volumes_list2}}.{{test_id }}"

#- name: Creation de la list des volumes attachés aux instances
#  set_fact:
#    test2: "{{item}}"
#  loop: "{{ query('volumes_list2', 'h9999ad1') }}"
