---
- name: Init list
  set_fact:
    windows_instances_list_name: []

#- debug:
#    msg: "{{ item }}"
#  loop: "{{ query('inventory_hostnames', 'all:!meta-is_windows_true') }}"

- name: Creation de la list des serveurs windows
  set_fact:
    windows_instances_list_name: "{{ windows_instances_list_name }} + ['{{item}}']"
  with_items: "{{ groups['meta-is_windows_true'] }}"

- os_auth:
- os_client_config:
  register: client_conf

- name: Get openstack projects list
  uri:
    url: "https://fr-east-2.pub.hopla.cloud:13000/v3/auth/projects"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ auth_token }}"
  register: projects_list_os

- name: Set project id
  set_fact:
    project_id: "{{projects_list_os.json.projects[0].id}}"

- name: Get openstack volumes list
  uri:
    url: "https://fr-east-2.pub.hopla.cloud:13776/v3/{{project_id}}/volumes"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ auth_token }}"
  register: volumes_list_os

- name: Creation des list name et id
  set_fact:
    volumes_name: "{{ volumes_list_os.json.volumes | json_query('[].name') }}"
    volumes_id: "{{ volumes_list_os.json.volumes | json_query('[].id') }}"

- name: Create list volumes_id and volumes_name
  set_fact:
    volumes_list1: "{{ dict(volumes_id | zip(volumes_name)) }}"
    volumes_list2: "{{ dict(volumes_name | zip(volumes_id)) }}"

#- name: Creation de la list des volumes attachés aux instances
#  set_fact:
#    "windows_disk_{{item}}": "{{hostvars[item]['openstack'].volumes}}"
#  with_items: "{{ windows_instances_list_name }}"
#
#- debug:
#    msg: "{{ volumes_list2 | dict2items | selectattr('key', 'match', item) | list | items2dict }}"
#  with_items: "{{ windows_instances_list_name }}"
#- name: Get filer volume
#  shell: |
#   echo "{{volumes_list2}}" | sed "s/\,/\n/g" | egrep "{{item}}" | egrep _filer | awk -F ": " '{ print $2 }'
#  register: "{{item}}_filer"
#  with_items: "{{ windows_instances_list_name }}"
#  changed_when: false
