---
# tasks file for hoplacloud.windows_dev

- name: Get DistinguishedName
  win_shell: (Get-ADDomain).DistinguishedName
  register: ad_domain
  changed_when: ad_domain.rc == 1

- name: Set facts
  set_fact:
    ad_domain: "{{ ad_domain.stdout_lines[0] }}"
    ad_session_host_list: "{{groups['meta-is_rds_std_true'] | map('regex_replace', '$', '.') | list}}"
#    ad_session_host: "{{groups['meta-is_rds_std_true'][0]}}"
#    ad_session_host_list: "{{groups['meta-is_rds_std_true'] | map(‘regex_replace’, ‘$’, ‘’) | list}}"
#    ad_session_host_list: "{{groups['meta-is_rds_std_true']| join(',')}}"

- set_fact:
    ad_session_host_list: "{{ad_session_host_list | map('regex_replace', '$', ad_domain_name) | list}}"
    comma: '","'
#- set_fact:
#    ad_session_host_list: "{{ad_session_host_list | map('regex_replace', '$', '\"') | list}}"
#- set_fact:
#    ad_session_host_list: "{{ad_session_host_list | map('regex_replace', '^(.*)$', '\"\\1') | list}}"
- set_fact:
    ad_session_host_list: "{{ad_session_host_list | join(',')}}"
- name: Set pw facts
  win_shell: |
    $ad_session_hosts="{{ad_session_host_list}}"
    Write-Host $ad_session_hosts
    }
- name: Set fact1
  set_fact:
    ad_session_hosts: "{{ad_session_host_list}}"
    ad_connection_broker: "{{ansible_fqdn}}"
    ad_web_access: "{{ansible_fqdn}}"
    ad_license: "{{ansible_fqdn}}"

- name: Create directory scripts
  win_file:
    path: C:\scripts
    state: directory

- name: Create RD Deployement script
  win_template:
    src: RD_Session_Deployment.ps1.j2
    dest: C:\scripts\RD_Session_Deployment.ps1
