---
# tasks file for hoplacloud.windows_dev

- name: Get DistinguishedName
  win_shell: (Get-ADDomain).DistinguishedName
  register: ad_domain
  changed_when: ad_domain.rc == 1

- name: Set facts
  set_fact:
    ad_domain: "{{ ad_domain.stdout_lines[0] }}"
#    ad_session_host_list: "{{groups['meta-is_rds_std_true'] | map(‘regex_replace’, ‘$’, ‘’) | list}}"
#    ad_session_host_list: "{{groups['meta-is_rds_std_true']| join(',')}}"


- set_fact:
    ad_session_host_list: "{{groups['meta-is_rds_std_true'] | map('regex_replace', '$', 'ad_domain') | list}}"

- name: Set fact1
  set_fact:
    ad_session_host: "\"{{ad_session_host_list}}\""
    ad_connection_broker: "{{ansible_fqdn}}"
    ad_web_access: "{{ansible_fqdn}}"

- name: Set fact3
  set_fact:
    ad_session_host: "{{ad_session_host | regex_replace(',', '\",\"')}}"
- debug:
    msg: System {{ ad_session_host }}
#- name: Create collection
#  win_shell: |
#    if (!(Get-RDServer -erroraction 'silentlycontinue')){
#    New-RDSessionDeployment -SessionHost @("{{ad_session_host}}") -ConnectionBroker "{{ad_connection_broker}}" -WebAccessServer "{{ad_web_access}}"
#    New-RDSessionCollection -CollectionName "Default" -SessionHost  @("{{ad_session_host}}") -ConnectionBroker "{{ad_connection_broker}}"
#    Set-RDLicenseConfiguration -LicenseServer "{{ansible_fqdn}}" -ConnectionBroker "{{ad_connection_broker}}" -Mode PerUser
#    Write-Host Change
#    }
#  register: ad_collection
#  changed_when: ("Change" in ad_collection.stdout)
