---
# tasks file for hoplacloud.windows-dev
- name: Get all facts
  setup:

- name: Disable firewall
  win_firewall:
    state: disabled

- name: Ensure user Admin account password never expire
  win_user:
    name: admin
    password_never_expires: yes
    update_password: on_create

- name: Ensure user Administrator is disabled
  win_user:
    name: administrator
    account_disabled: yes

- name: Set windows edition to datacenter
  win_shell: |
    dism /online /set-edition:ServerDatacenter /ProductKey:WMDGN-G9PQG-XVVXX-R3X43-63DFG /AcceptEula
    n
  when: ansible_os_name == "Microsoft Windows Server 2019 Datacenter Evaluation"

- name: Reboot server
  win_reboot:
    reboot_timeout: 3600

- name: Install all security, critical, and rollup updates without a scheduled task and reboot if needed.
  win_updates:
    reboot: yes
