---
# tasks file for hoplacloud.windows_dev

- name: Get DistinguishedName
  win_shell: (Get-ADDomain).DistinguishedName
  register: ad_domain
  changed_when: ad_domain.rc == 1

- name: Set fact ad_domain
  set_fact:
    ad_domain: "{{ ad_domain.stdout_lines[0] }}"

- name: Get RDS session hosts
  win_shell: |
    (Get-ADComputer -SearchBase "OU=RDS,OU=Servers,OU=ORGANIZATION,{{ad_domain}}" -Filter *).DNSHostName
  register: ad_session_host_list

- name: Set fact rd servers
  set_fact:
    ad_session_host_2: "{{groups['meta-is_rds_std_true']}}"

#- name: Set fact rd servers
#  set_fact:
#    ad_session_host: "{{ad_session_host_list.stdout | join('\n')}}"
  #with_item: ad_session_host_list.stdout

- name: Set fact rd servers
  set_fact:
    #ad_session_host: "{{ad_ad_session_host_list.stdout}}"
    ad_connection_broker: "{{ansible_fqdn}}"
    ad_web_access: "{{ansible_fqdn}}"
