---
# tasks file for hoplacloud.windows_dev

- name: Get DistinguishedName
  win_shell: (Get-ADDomain).DistinguishedName
  register: ad_domain
  changed_when: ad_domain.rc == 1

- name: Set facts
  set_fact:
    ad_domain: "{{ ad_domain.stdout_lines[0] }}"
    ad_session_host_list: "{{groups['meta-is_rds_std_true'] | map('regex_replace', '$', '.') | list}}"
#    ad_session_host_list: "{{groups['meta-is_rds_std_true'] | map(‘regex_replace’, ‘$’, ‘’) | list}}"
#    ad_session_host_list: "{{groups['meta-is_rds_std_true']| join(',')}}"

- set_fact:
    ad_session_host_list: "{{ad_session_host_list | map('regex_replace', '$', ad_domain_name) | list}}"
#- set_fact:
#    ad_session_host_list: "{{ad_session_host_list | map('regex_replace', '$', '\"') | list}}"
#- set_fact:
#    ad_session_host_list: "{{ad_session_host_list | map('regex_replace', '^(.*)$', '\"\\1') | list}}"
#- set_fact:
#    ad_session_host_list: "{{ad_session_host_list | regex_replace(',', '\",\"')}}"
- name: Set fact1
  set_fact:
    ad_session_host: "{{ad_session_host_list | join(',')}}"
    ad_connection_broker: "{{ansible_fqdn}}"
    ad_web_access: "{{ansible_fqdn}}"
    ad_license: "{{ansible_fqdn}}"

- debug:
    msg: System {{ ad_session_host }}
- name: Create collection
  win_shell: |
    if (!(Get-RDServer -erroraction 'silentlycontinue')){
    $ad_session_host="{{ad_session_host}}"
    $ad_session_host=$ad_session_host -replace ",", '","'
    $ad_session_host=$ad_session_host -replace "^", '"'
    $ad_session_host=$ad_session_host -replace "$", '"'
    Write-Host $ad_session_host
    $ad_connection_broker="{{ad_connection_broker}}"
    Write-Host $ad_connection_broker
    $ad_web_access="{{ad_web_access}}"
    Write-Host $ad_web_access
    $ad_license="{{ad_license}}"
    Write-Host $ad_license
    New-RDSessionDeployment -SessionHost @($ad_session_host) -ConnectionBroker $ad_connection_broker -WebAccessServer $ad_web_access
    New-RDSessionCollection -CollectionName "Default" -SessionHost  @($ad_session_host) -ConnectionBroker $ad_connection_broker
    Set-RDLicenseConfiguration -LicenseServer $ad_license -ConnectionBroker $ad_connection_broker -Mode PerUser
    Write-Host Change
    }
  register: ad_collection
  changed_when: ("Change" in ad_collection.stdout)
