---
- os_auth:
- os_client_config:
  register: client_conf

- name: Get
  uri:
    url: "https://fr-east-1.pub.hopla.cloud:13776/v3/{{ client_conf.ansible_facts.openstack.clouds[0].auth.project_id }}/volumes"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ auth_token }}"
  register: volumes_list_os

- set_fact:
  volumes_name: "{{ volumes_list_os.json.volumes | json_query('[].name') }}"
  volumes_id: "{{ volumes_list_os.json.volumes | json_query('[].id') }}"

- name: populate volumes list
  set_fact:
    volumes_list: "{{ combined_var|default({}) | combine({ item.0: item.1 }) }}"
  loop: "{{ query('together', volumes_id, volumes_name) }}"
