---
- name: Get offlines volumes id
  win_shell: |
    $disks=(get-disk | Where-Object OperationalStatus -eq "Offline").SerialNumber
    write-host $disks
  register: vol_id

- name: Creation de la list des volumes attaches
  set_fact:
    vol_attach: "{{ hostvars['localhost'].volumes_list2 | dict2items | selectattr('key', 'match', ansible_hostname) | list | items2dict }}"

- name: Rechercher des types de volumes
  set_fact:
    vol_filer: "{{ vol_attach | dict2items | selectattr('key', 'match', filer) | list | items2dict }}"
    vol_profiles: "{{ vol_attach | dict2items | selectattr('key', 'match', profiles) | list | items2dict }}"

#- name: Mount all offlines volumes
#  win_shell: |
#    $off_disk=(Get-Disk | Where-Object OperationalStatus -eq "Offline")
#    if ($off_disk){
#    $off_disk | Set-Disk -IsOffline $False
#    $off_disk | Initialize-Disk -PartitionStyle GPT
#    $off_disk | New-Partition -UseMaximumSize -AssignDriveLetter | Format-Volume
#    Write-Host Change
#    }
#  register: ad_volumes_init
#  changed_when: ("Change" in ad_volumes_init.stdout)
