---
# tasks file for hoplacloud.windows_rds_gw
- name: Install RDS GW, Broker, Web acces and Licensing with sub features and management tools
  win_feature:
    name:
    - RDS-Licensing
    - RDS-Web-Access
    - RDS-Connection-Broker
    - RDS-Gateway
    state: present
    include_sub_features: yes
    include_management_tools: yes

- name: Create directory scripts
  win_file:
    path: C:\scripts
    state: directory

- name: Install Certify
  win_chocolatey:
    name: certifytheweb
    ignore_checksums: yes
    state: present

- name: Copy certify script
  win_copy:
    src: Renew-cert-RDS.ps1
    dest: C:\scripts\Renew-cert-RDS.ps1

- name: Set facts
  set_fact:
    ad_session_host_list: "{{groups['meta-is_rds_host_true'] | map('regex_replace', '$', '.') | list}}"
- set_fact:
    ad_session_host_list: "{{ad_session_host_list | map('regex_replace', '$', ad_domain_name) | list}}"
- set_fact:
    ad_session_host_list: "{{ad_session_host_list | join(',')}}"

- name: Create session hosts list facts
  win_shell: |
    $ad_session_hosts="{{ad_session_host_list}}"
    $ad_session_hosts=$ad_session_hosts -replace ",", '","'
    Write-Host $ad_session_hosts
  register: ad_session_host_fact
  changed_when: ("Change" in ad_session_host_fact.stdout)

- name: Set fact for rds Deployement
  set_fact:
    ad_session_hosts: "{{ad_session_host_fact.stdout_lines[0]}}"
    ad_connection_broker: "{{ansible_fqdn}}"
    ad_web_access: "{{ansible_fqdn}}"
    ad_license: "{{ansible_fqdn}}"
    ad_gw_fqdn: "desk.{{ad_domain_name}}"

- name: Create RD Deployement script
  win_template:
    src: RD_Session_Deployment.ps1.j2
    dest: C:\scripts\RD_Session_Deployment.ps1
