---
# tasks file for hoplacloud.windows_get_password
- set_fact:
      windows_instances_list_name: []
      windows_instances_list_id: []
      cpt_1: 0

- set_fact:
      windows_instances_list_name: "{{ windows_instances_list_name }} + ['{{item}}']"
      windows_instances_list_id: "{{windows_instances_list_id + [hostvars[item]['openstack']['id']]}}"
  with_items: "{{ groups['meta-is_windows_true'] }}"

#- set_fact:
#      "windows_instances_id_{{item}}": "tt"
#  with_items: "{{ groups['meta-is_windows_true'] }}"
#- debug: msg="host is {{ hostvars['h9999ad1']['openstack']['hostId'] }}"
#  with_items: "{{ groups['meta-is_windows_true'] }}"

- name: Get auth_token
  os_auth:

- name: Get instance password
  uri:
    url: "https://fr-east-1.pub.hopla.cloud:13774/v2.1/servers/{{ item }}/os-server-password"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ auth_token }}"
  register: password_crypt
  with_items: "{{ windows_instances_list_id }}"

- set_fact:
      "windows_instances_password_{{item}}": "{{ password_crypt.results[cpt_1|int].json.password }}"
      cpt_1: "{{cpt_1|int + 1}}"
  with_items: "{{ windows_instances_list_name }}"

#- debug: msg="{{cpt_1}}"

#- debug: msg="{{ [hostvars['localhost']] }}"

- name: Copy private key
  shell: echo "{{ private_key }}" > private_key.pem

- name: Get clear password
  shell: |
   echo "{{ windows_instances_password_ + item }}" \
   | openssl base64 -d \
   | openssl rsautl -decrypt -inkey private_key.pem -keyform PEM
   rm -f private_key.pem
  register: password_clear
  with_items: "{{ windows_instances_list_name }}"
