---
# tasks file for hoplacloud.windows_rds_standalone
- name: Get DistinguishedName
  win_shell: (Get-ADDomain).DistinguishedName
  register: ad_domain
  changed_when: ad_domain.rc == 1

- name: Set facts
  set_fact:
    ad_domain: "{{ ad_domain.stdout_lines[0] }}"
    ad_session_host_list: "{{groups['meta-is_rds_std_true'] | map('regex_replace', '$', '.') | list}}"
- set_fact:
    ad_session_host_list: "{{ad_session_host_list | map('regex_replace', '$', ad_domain_name) | list}}"
- set_fact:
    ad_session_host_list: "{{ad_session_host_list | join(',')}}"

- name: Set pw facts
  win_shell: |
    $ad_session_hosts="{{ad_session_host_list}}"
    $ad_session_hosts=$ad_session_hosts -replace ",", '","'
    Write-Host $ad_session_hosts
  register: ad_session_host_fact
  changed_when: ("Change" in ad_session_host_fact.stdout)

- name: Set fact1
  set_fact:
    ad_session_hosts: "{{ad_session_host_fact.stdout_lines[0]}}"
    ad_connection_broker: "{{ansible_fqdn}}"
    ad_web_access: "{{ansible_fqdn}}"
    ad_license: "{{ansible_fqdn}}"
    ad_gw_fqdn: "desk.{{ad_domain_name}}"

- name: Create RD Deployement script
  win_template:
    src: RD_Session_Deployment.ps1.j2
    dest: C:\scripts\RD_Session_Deployment.ps1
