---
# tasks file for hoplacloud.windows_rds_standalone

- name: Install Active Directory with sub features and management tools
  win_feature:
    name:
    - RDS-Connection-Broker
    - RDS-RD-Server
    - RDS-Web-Access
    - NET-Framework-Core
    state: present
    include_sub_features: yes
    include_management_tools: yes

- name: Create directory scripts
  win_file:
    path: C:\scripts
    state: directory

- name: Create directory odt
  win_file:
    path: C:\odt
    state: directory

- name: Copy office setup file
  win_copy:
    src: setup.exe
    dest: C:\odt\setup.exe

- name: Copy office config file
  win_copy:
    src: configuration.xml
    dest: C:\odt\configuration.xml

- name: Ensure Office is present
  win_shell: |
    $odt_check = (Get-ChildItem -Path "C:\odt").Name
    if ($odt_check -notcontains 'setup_office_ansible'){
    C:\odt\setup.exe /download
    C:\odt\setup.exe /configure
    New-Item -Name setup_office_ansible -ItemType File -Path C:\odt\
    Write-Host Change}
  register: rds_office_install
  changed_when: ("Change" in rds_office_install.stdout)

- name: Create directory scripts
  win_file:
    path: C:\scripts\fslogix
    state: directory

- name: Copy office config file
  win_copy:
    src: FSLogixAppsSetup.exe
    dest: C:\scripts\fslogix

- name: Ensure FSlogix is present
  win_shell: |
    $fslogix_check = (Get-ChildItem -Path C:\scripts\fslogix).Name
    if ($odt_check -notcontains 'fslogix_setup_ansible'){
    C:\scripts\fslogix\FSLogixAppsSetup.exe /install /quiet /norestart
    New-Item -Name fslogix_setup_ansible -ItemType File -Path C:\scripts\fslogix\
    Write-Host Change
    }
  register: rds_fslogix_install
  changed_when: ("Change" in rds_fslogix_install.stdout)

- name: Copy disconnect file
  win_copy:
    src: Disconnect.bat
    dest: C:\Users\Public\Desktop\

- name: Copy disconnect file
  win_copy:
    src: Disconnect.lnk
    dest: C:\Users\Public\Desktop\

#- name: Download TeamViewer
#  win_get_url:
#    url: https://get.teamviewer.com/iilyo-qs1
#    dest: C:\Users\Public\Desktop\Support iilyo.exe

- name: Install adobereader
  win_chocolatey:
    name: adobereader
    state: present
    package_params: NoUpdates

- name: Install apps
  win_chocolatey:
    name:
      - GoogleChrome
      - jre8
      - 7zip.install
      - irfanview
      - irfanviewplugins
    state: present
